name: send message

on:
    workflow_dispatch:
    schedule:
    - cron: "*/10 * * * *"  # 👉 매 10분마다 실행 (GitHub 서버 시간 기준)

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Compile and Run Bot
        run: |
          javac Webhook.java
          java Webhook
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY2: ${{ secrets.API_KEY2 }}
          API_URL: ${{ secrets.API_URL }}
          API_URL2: ${{ secrets.API_URL2 }}
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}